# Generated by Django 4.2.4 on 2023-08-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaaSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
