# Generated by Django 4.2.4 on 2023-08-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaaSApp', '0003_project_description_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='entered_by',
        ),
    ]
